# Generated by Django 4.2.23 on 2026-09-26 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicalprofile', '0004_profilemedical_consultation_price_and_more'),
        ('core', '0013_userprofile'),
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('appointment_time', models.TimeField(verbose_name='Hora de la cita')),
                ('appointment_date', models.DateField(verbose_name='Fecha de la cita')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo de la consulta')),
                ('consultation_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalprofile.consultationschedule', verbose_name='Horario de consulta')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalprofile.profilemedical', verbose_name='Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.profilepatient', verbose_name='Paciente')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.specialty', verbose_name='Especialidad')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
            },
        ),
    ]
