# Generated by Django 4.2.23 on 2026-09-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de atención'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Motivo de cancelación'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('paciente', 'Paciente'), ('medico', 'Médico'), ('sistema', 'Sistema')], default='', max_length=20, verbose_name='Cancelada por'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='indications',
            field=models.TextField(blank=True, null=True, verbose_name='Indicaciones'),
        ),
    ]
