# Generated by Django 4.2.23 on 2026-09-26 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0002_appointment_attended_at_appointment_cancel_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescribedMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, verbose_name='Medicamento')),
                ('dose', models.CharField(max_length=100, verbose_name='Dosis')),
                ('frequency', models.CharField(max_length=100, verbose_name='Frecuencia')),
                ('duration', models.CharField(blank=True, default='', max_length=100, verbose_name='Duración')),
                ('route', models.CharField(blank=True, default='', max_length=50, verbose_name='Vía de administración')),
                ('instructions', models.CharField(blank=True, default='', max_length=255, verbose_name='Indicaciones')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='appointment.appointment', verbose_name='Cita')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicamento prescrito',
                'verbose_name_plural': 'Medicamentos prescritos',
                'ordering': ['order', 'id'],
            },
        ),
    ]
