# Generated by Django 4.2.23 on 2026-09-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_prescribedmedication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('paciente', 'Paciente'), ('medico', 'Médico'), ('sistema', 'Sistema'), ('administrativo', 'Administrativo')], default='', max_length=20, verbose_name='Cancelada por'),
        ),
    ]
