# Generated by Django 4.2.23 on 2025-06-14 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_rename_persona_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('aboutme', models.TextField(default='', max_length=100, verbose_name='About me profile')),
                ('isprincipal', models.BooleanField(default=True, verbose_name='Is principal profile')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Profile Medical',
                'verbose_name_plural': 'Profiles Medical',
            },
        ),
        migrations.CreateModel(
            name='TypeProfileMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Type Profile Medical',
                'verbose_name_plural': 'Types Profiles Medical',
            },
        ),
        migrations.CreateModel(
            name='SpecialtyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('isprincipal', models.BooleanField(default=True, verbose_name='Is principal profile')),
                ('profilemedical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalprofile.profilemedical', verbose_name='Perfil medico')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.specialty', verbose_name='Especialidad de perfil medico')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Speciality Profile Medical',
                'verbose_name_plural': 'Specialities Profiles Medical',
            },
        ),
        migrations.AddField(
            model_name='profilemedical',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalprofile.typeprofilemedical', verbose_name='Tipo de perfil medico'),
        ),
        migrations.AddField(
            model_name='profilemedical',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilemedical',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
