# Generated by Django 4.2.23 on 2025-06-28 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('consultation_duration', models.DurationField(verbose_name='Duración de consulta')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalprofile.profilemedical', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Horario de consulta',
                'verbose_name_plural': 'Horarios de consulta',
            },
        ),
    ]
