# Generated by Django 4.2.23 on 2025-06-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalprofile', '0002_consultationschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationschedule',
            name='available_days',
            field=models.CharField(blank=True, choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], help_text='Días de la semana en los que el doctor está disponible para consultas.', max_length=50, null=True, verbose_name='Días disponibles'),
        ),
    ]
