# Generated by Django 4.2.23 on 2026-09-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalprofile', '0003_consultationschedule_available_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemedical',
            name='consultation_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio de consulta'),
        ),
        migrations.AddField(
            model_name='profilemedical',
            name='office',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Consultorio'),
        ),
        migrations.AddField(
            model_name='profilemedical',
            name='years_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Años de experiencia'),
        ),
        migrations.AlterField(
            model_name='profilemedical',
            name='aboutme',
            field=models.TextField(default='', verbose_name='About me profile'),
        ),
    ]
