# Generated by Django 4.2.23 on 2025-06-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
