# Generated by Django 4.2.23 on 2025-06-12 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_entity_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusentity',
            name='detail_one',
        ),
        migrations.RemoveField(
            model_name='aboutusentity',
            name='detail_three',
        ),
        migrations.RemoveField(
            model_name='aboutusentity',
            name='detail_two',
        ),
        migrations.CreateModel(
            name='AboutUsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('title', models.TextField(default='', verbose_name='Title')),
                ('decription', models.TextField(default='', verbose_name='Description about us')),
                ('icon', models.CharField(default='', max_length=100, verbose_name='icon')),
                ('aboutus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aboutusentity', verbose_name='About Us Entity')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'About Us detail',
                'verbose_name_plural': 'About Us details',
            },
        ),
    ]
