# Generated by Django 4.2.23 on 2025-06-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_aboutusentity_detail_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusentity',
            name='picturevideo',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
