# Generated by Django 4.2.23 on 2025-06-14 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Canton',
                'verbose_name_plural': 'Cantones',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('canton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.canton', verbose_name='Canton')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parish',
                'verbose_name_plural': 'Parishes',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='Country')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Province',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('names', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('lastnames', models.CharField(default='', max_length=50, verbose_name='1er Apellido')),
                ('document', models.CharField(blank=True, default='', max_length=20, verbose_name='Cedula')),
                ('typedocument', models.IntegerField(choices=[(1, 'CEDULA'), (2, 'RUC'), (3, 'PASAPORTE'), (4, 'PASAPORTE'), (5, 'OTRO')], default=1, verbose_name='Tipo de documento')),
                ('birthdate', models.DateField(verbose_name='Fecha de nacimiento o constitución')),
                ('sexo', models.IntegerField(choices=[(1, 'MASCULINO'), (2, 'FEMENINO')], default=1, verbose_name='Sexo')),
                ('nacionality', models.CharField(default='', max_length=100, verbose_name='Nacionalidad')),
                ('ciudadela', models.CharField(default='', max_length=300, verbose_name='Ciudadela')),
                ('sector', models.CharField(default='', max_length=300, verbose_name='Sector de residencia')),
                ('city', models.CharField(default='', max_length=50, verbose_name='Ciudad de residencia')),
                ('streetaddress', models.CharField(default='', max_length=300, verbose_name='Calle principal')),
                ('secondarystreetaddress', models.CharField(default='', max_length=300, verbose_name='Calle secundaria')),
                ('numberstreet', models.CharField(default='', max_length=15, verbose_name='Numero')),
                ('reference', models.CharField(default='', max_length=100, verbose_name='Referencia')),
                ('cellphonenumber', models.CharField(default='', max_length=50, verbose_name='Telefono movil')),
                ('telefonenumber', models.CharField(default='', max_length=50, verbose_name='Telefono fijo')),
                ('email', models.CharField(default='', max_length=200, verbose_name='Correo electronico personal')),
                ('emailinst', models.CharField(default='', max_length=200, verbose_name='Correo electronico institucional')),
                ('birthdatecanton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birthdatecanton_set', to='core.canton', verbose_name='Canton de nacimiento')),
                ('birthdatecountry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birthdatecountry_set', to='core.country', verbose_name='País de nacimiento')),
                ('birthdateparish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birthdateparish_set', to='core.parish', verbose_name='Parroquia de nacimiento')),
                ('birthdateprovince', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birthdateprovince_set', to='core.province', verbose_name='Provincia de nacimiento')),
                ('canton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canton_set', to='core.canton', verbose_name='Canton de residencia')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_set', to='core.country', verbose_name='País residencia')),
                ('nacinalitycountry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nacinalitycountry_set', to='core.country', verbose_name='País de nacionalidad')),
                ('parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parish_set', to='core.parish', verbose_name='Parroquia de residencia')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_set', to='core.province', verbose_name='Provincia de residencia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='canton',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='canton',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canton',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
