# Generated by Django 4.2.23 on 2025-06-14 19:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_canton_country_parish_province_persona_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Person',
        ),
    ]
