# Generated by Django 4.2.23 on 2025-06-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_persona_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Ciudad de residencia'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ciudadela',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Ciudadela'),
        ),
        migrations.AlterField(
            model_name='person',
            name='emailinst',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Correo electronico institucional'),
        ),
        migrations.AlterField(
            model_name='person',
            name='numberstreet',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='person',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='person',
            name='secondarystreetaddress',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Calle secundaria'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Sector de residencia'),
        ),
        migrations.AlterField(
            model_name='person',
            name='streetaddress',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Calle principal'),
        ),
        migrations.AlterField(
            model_name='person',
            name='telefonenumber',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Telefono fijo'),
        ),
    ]
