# Generated by Django 4.2.23 on 2025-06-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_person_city_alter_person_ciudadela_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
    ]
