# Generated by Django 4.2.23 on 2025-06-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='front_page_profile',
            field=models.FileField(blank=True, null=True, upload_to='front_page/'),
        ),
        migrations.AddField(
            model_name='person',
            name='front_page_target',
            field=models.FileField(blank=True, null=True, upload_to='front_page/'),
        ),
    ]
