# Generated by Django 4.2.23 on 2025-06-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_person_front_page_profile_person_front_page_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='front_page_target',
            new_name='front_page_card',
        ),
    ]
