# Generated by Django 4.2.23 on 2026-09-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Debe cambiar la contraseña'),
        ),
    ]
