# Generated by Django 4.2.23 on 2025-06-28 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicalprofile', '0002_consultationschedule'),
        ('core', '0012_rename_front_page_target_person_front_page_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la alergia')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alergy',
                'verbose_name_plural': 'Alergies',
            },
        ),
        migrations.CreateModel(
            name='CheckPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('appointment_date', models.DateTimeField(verbose_name='Fecha de la consulta')),
                ('status_check', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('snapshot', models.TextField(blank=True, null=True, verbose_name='Resumen médico de la comsulta')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalprofile.profilemedical', verbose_name='Médico')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Paciente')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.specialty', verbose_name='Especialidad')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Check',
                'verbose_name_plural': 'Checks',
            },
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la enfermedad')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enfermedad',
                'verbose_name_plural': 'Enfermedades',
            },
        ),
        migrations.CreateModel(
            name='LabAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del análisis')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laboratory Analysis',
                'verbose_name_plural': 'Laboratory Analysis',
            },
        ),
        migrations.CreateModel(
            name='PatientIllness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('status_check', models.CharField(choices=[('padeciendo', 'Padeciendo'), ('curada', 'Curada'), ('recaida', 'Recaida')], default='padeciendo', max_length=20)),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.illness', verbose_name='Enfermedad')),
            ],
            options={
                'verbose_name': 'Enfermedad',
                'verbose_name_plural': 'Enfermedades',
            },
        ),
        migrations.CreateModel(
            name='ProfilePatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('medical_record_number', models.CharField(max_length=20, unique=True, verbose_name='Número de historia clínica')),
                ('diabetes', models.BooleanField(default=False, verbose_name='Diabetes')),
                ('blood_pressure', models.CharField(blank=True, max_length=50, null=True, verbose_name='Presión arterial')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Peso')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Altura')),
                ('insurance_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de seguro')),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True, verbose_name='Grupo sanguíneo')),
                ('rh_factor', models.CharField(blank=True, max_length=3, null=True, verbose_name='Factor RH')),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Persona')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Patient',
                'verbose_name_plural': 'Profiles Patients',
            },
        ),
        migrations.CreateModel(
            name='PatientTherapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('patientillnes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.patientillness', verbose_name='Enfermedad')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Therapy',
                'verbose_name_plural': 'Patients Therapies',
            },
        ),
        migrations.CreateModel(
            name='PatientLabAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(verbose_name='Fecha del análisis')),
                ('checkpatient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.checkpatient', verbose_name='Consulta médica')),
                ('lab_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.labanalysis', verbose_name='Análisis de laboratorio')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.profilepatient', verbose_name='Paciente')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Laboratories Analysis',
                'verbose_name_plural': 'Patients Laboratories Analysis',
            },
        ),
        migrations.AddField(
            model_name='patientillness',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.profilepatient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='patientillness',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientillness',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PatientAlergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('alergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.alergy', verbose_name='Alergia')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.profilepatient', verbose_name='Paciente')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Alergy',
                'verbose_name_plural': 'Patient Alergies',
            },
        ),
    ]
