# Generated by Django 4.2.23 on 2026-09-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepatient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='profilepatient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono del contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='profilepatient',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Parentesco del contacto de emergencia'),
        ),
    ]
